import { EncodeDecoder, fpToTsEncDec } from '../plugin/encodedecoder';
import {
  FpInterfaceType,
  InterfaceKind,
  RetType,
  TsInterfaceType,
  WithInterfaceTag
} from '../plugin/interfacekind';
import { toFailablePromise } from './pluginhost';

/**
 * Represents the response from an authentication request, encapsulating the status
 * and message related to the authentication process, along with a method for serialization.
 */
export interface IsAuthResponse {
  /** Indicates the level of authentication achieved.
   *  - `'full'` indicates that the all the plugins have authenticated the user.
   *  - `'partial'` indicates that some of the plugins have authenticated the user.
   *  - `'none'` indicates that none of the plugins have authenticated the user.
   */
  authStatus: 'full' | 'partial' | 'none';

  /** A descriptive message providing details about the authentication process or its outcome. */
  authMessage: string;
}

/**
 * Defines the structure for an authentication mapper, responsible for handling
 * authentication processes, including requesting authentication, validating responses,
 * and extracting information necessary for validity checks.
 *
 * @template AuthResponse The type of the authentication response.
 * @template AuthResponseValidityCheck The type used for checking the validity of an auth response.
 * @template AuthValidityReport The type representing the outcome of the validity check.
 */
export interface IAuthMapper<
  InterfaceType extends InterfaceKind,
  AuthResponse extends IsAuthResponse,
  AuthResponseValidityCheck,
  AuthValidityReport
> extends WithInterfaceTag<InterfaceType> {
  /**
   * Asynchronously requests authentication based on the provided request body.
   * @param authRequestBody The request body for the authentication request.
   * @returns A promise resolving to an `AuthResponse`.
   */
  requestAuth(authRequestBody: unknown): RetType<InterfaceType, AuthResponse>;

  /**
   * Asynchronously checks the validity of an authentication response.
   * @param authResponse The response to validate.
   * @returns A promise resolving to an `AuthValidityReport`.
   */
  checkAuthValidity(
    authResponse: AuthResponseValidityCheck
  ): RetType<InterfaceType, AuthValidityReport>;

  /**
   * Extracts necessary information from an `AuthResponse` to perform a validity check.
   * @param authResponse The authentication response.
   * @returns The extracted information necessary for the validity check.
   */
  extractValidityCheck(authResponse: AuthResponse): AuthResponseValidityCheck;

  /**
   * Provide an encoder/decoder for the authentication response.
   * Use it to make sure that it is in a serializable format
   */
  readonly authResponseEncDecoder: EncodeDecoder<InterfaceType, AuthResponse>;
}

/**
 * Transforms the result of the `checkAuthValidity` method of an `IAuthMapper` instance,
 * allowing for the transformation of the validity report into a new type.
 *
 * @template T The type of the authentication response, extending `IsAuthResponse`.
 * @template A The original type of the validity report generated by `checkAuthValidity`.
 * @template V The type of the input to `checkAuthValidity`.
 * @template B The new type for the validity report after transformation.
 * @param authMapper An instance of `IAuthMapper`.
 * @param f A function that transforms a value of type `A` into a `Promise<B>`.
 * @returns An `IAuthMapper` instance with transformed `checkAuthValidity` output.
 */
export const mapValidityReport = <T extends IsAuthResponse, A, V, B>(
  authMapper: IAuthMapper<TsInterfaceType, T, V, A>,
  f: (a: A) => Promise<B>
): IAuthMapper<TsInterfaceType, T, V, B> => {
  return {
    __interface_tag: 'ts',
    extractValidityCheck: authMapper.extractValidityCheck,
    requestAuth: authMapper.requestAuth,
    authResponseEncDecoder: authMapper.authResponseEncDecoder,
    checkAuthValidity: (input: V): Promise<B> => {
      return authMapper.checkAuthValidity(input).then(f);
    }
  };
};

export const fpToTsAuthMapper = <T extends IsAuthResponse, V, A>(
  authMapper: IAuthMapper<FpInterfaceType, T, V, A>
): IAuthMapper<TsInterfaceType, T, V, A> => {
  return {
    __interface_tag: 'ts',
    extractValidityCheck: authMapper.extractValidityCheck,
    requestAuth: (x) => toFailablePromise(authMapper.requestAuth(x)),
    authResponseEncDecoder: fpToTsEncDec(authMapper.authResponseEncDecoder),
    checkAuthValidity: (x) => toFailablePromise(authMapper.checkAuthValidity(x))
  };
};
